import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Komal',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Kamlesh',
      email: 'kamleshsaini@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      slideImage: '/images/slider/slider1.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality nike shirts',
    },
    {
      // _id: '2',
      name: 'Nike slim girls T-shirts',
      slug: 'nike-slim-girls-tshirt',
      category: 't-shirts',
      image: '/images/p2.jpg',
      slideImage: '/images/slider/slider2.png',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality nike t-shirts',
    },
    {
      // _id: '3',
      name: 'Adidas fit pants',
      slug: 'adidas-slim-fit-pants',
      category: 'pants',
      image: '/images/p3.jpg',
      slideImage: '/images/slider/slider3.png',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 14,
      description: 'High quality adidas pants',
    },
    {
      // _id: '4',
      name: 'Adidas slim t-shirts',
      slug: 'adidas-slim-tshirts',
      category: 't-shirts',
      image: '/images/p4.jpg',
      slideImage: '/images/slider/slider4.png',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality adidas t-shirts',
    },
  ],
};

export default data;
