const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-2',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality shirts',
    },
    {
      name: 'Adidas fit shirt',
      slug: 'nike-slim-shirt-3',
      category: 'shirts',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 14,
      description: 'high quality shirts',
    },
    {
      name: 'Nike slim pant',
      slug: 'nike-slim-shirt-4',
      category: 'shirts',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
  ],
};

export default data;
